"""schema v1 — the 10 tables of ENGINEERING.md §2

Autogenerated from app.models, then hand-edited for the parts autogenerate
can't see: the vector extension, the audit_log immutability trigger, and
the configurable embedding dimension.

Revision ID: 0001
Revises:
Create Date: 2026-07-17

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.config import get_settings

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Needed before any vector column exists; Neon and the compose image
    # both ship the extension but don't enable it per-database.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "audit_log",
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("check_run_id", sa.BigInteger(), nullable=True),
        sa.Column("prompt_version", sa.String(length=100), nullable=True),
        sa.Column("input_hash", sa.String(length=128), nullable=True),
        sa.Column("agreement_score", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_check_run_id"), "audit_log", ["check_run_id"], unique=False)
    # Immutability, enforced IN the database. A trigger — not a REVOKE —
    # because the app role is the table owner (and locally a superuser),
    # so privilege revocation is a silent no-op for it (verified live,
    # V-003 research 2026-07-17). The REVOKE below is defense-in-depth for
    # environments where the connecting role is neither.
    op.execute(
        """
        CREATE FUNCTION audit_log_block_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log is append-only';
        END $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_log_immutable
        BEFORE UPDATE OR DELETE ON audit_log
        FOR EACH STATEMENT EXECUTE FUNCTION audit_log_block_mutation()
        """
    )
    op.execute("REVOKE UPDATE, DELETE ON audit_log FROM PUBLIC")
    op.create_table(
        "instructor",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instructor")),
        sa.UniqueConstraint("email", name=op.f("uq_instructor_email")),
    )
    op.create_table(
        "manuscript",
        sa.Column("instructor_id", sa.BigInteger(), nullable=False),
        sa.Column("group_label", sa.String(length=200), nullable=False),
        sa.Column("file_ref", sa.String(length=1024), nullable=False),
        sa.Column(
            "ingest_status",
            sa.Enum(
                "pending", "processing", "done", "failed", name="ingeststatus", native_enum=False
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("section_tree", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("submitted_by", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instructor_id"],
            ["instructor.id"],
            name=op.f("fk_manuscript_instructor_id_instructor"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manuscript")),
    )
    op.create_index(
        op.f("ix_manuscript_instructor_id"), "manuscript", ["instructor_id"], unique=False
    )
    op.create_table(
        "rubric",
        sa.Column("instructor_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "rubric_family_id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("source_file", sa.String(length=1024), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instructor_id"], ["instructor.id"], name=op.f("fk_rubric_instructor_id_instructor")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rubric")),
        sa.UniqueConstraint("rubric_family_id", "version", name=op.f("uq_rubric_rubric_family_id")),
    )
    op.create_index(op.f("ix_rubric_instructor_id"), "rubric", ["instructor_id"], unique=False)
    op.create_table(
        "check_run",
        sa.Column("manuscript_id", sa.BigInteger(), nullable=False),
        sa.Column("rubric_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "ingesting",
                "structural",
                "semantic",
                "integrity",
                "aggregating",
                "done",
                "failed",
                name="checkrunstatus",
                native_enum=False,
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("stage_status", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["manuscript_id"], ["manuscript.id"], name=op.f("fk_check_run_manuscript_id_manuscript")
        ),
        sa.ForeignKeyConstraint(
            ["rubric_id"], ["rubric.id"], name=op.f("fk_check_run_rubric_id_rubric")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_check_run")),
    )
    op.create_index(
        op.f("ix_check_run_manuscript_id"), "check_run", ["manuscript_id"], unique=False
    )
    op.create_index(op.f("ix_check_run_rubric_id"), "check_run", ["rubric_id"], unique=False)
    op.create_table(
        "criterion",
        sa.Column("rubric_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("structural", "semantic", name="criteriontype", native_enum=False),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.Column("weight", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rubric_id"],
            ["rubric.id"],
            name=op.f("fk_criterion_rubric_id_rubric"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_criterion")),
    )
    op.create_index(op.f("ix_criterion_rubric_id"), "criterion", ["rubric_id"], unique=False)
    op.create_table(
        "manuscript_archive",
        sa.Column("manuscript_id", sa.BigInteger(), nullable=False),
        # Dim from settings (EMBEDDING_DIM), baked in at migration time; must be
        # ≤ 2000 for the HNSW index below (pgvector limit, verified 2026-07-17).
        sa.Column(
            "embedding", pgvector.sqlalchemy.Vector(get_settings().embedding_dim), nullable=False
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["manuscript_id"],
            ["manuscript.id"],
            name=op.f("fk_manuscript_archive_manuscript_id_manuscript"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manuscript_archive")),
        sa.UniqueConstraint("manuscript_id", name=op.f("uq_manuscript_archive_manuscript_id")),
    )
    op.create_index(
        "ix_manuscript_archive_embedding",
        "manuscript_archive",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_table(
        "check_result",
        sa.Column("check_run_id", sa.BigInteger(), nullable=False),
        sa.Column("criterion_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "structural",
                "semantic",
                "internal_agreement",
                "citation_integrity",
                "statistical_forensics",
                "originality_reuse",
                name="checkkind",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.Enum(
                "passed",
                "failed",
                "escalated",
                "not_applicable",
                "unverifiable",
                "api_down",
                "quota_exhausted",
                name="resultoutcome",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["check_run_id"],
            ["check_run.id"],
            name=op.f("fk_check_result_check_run_id_check_run"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["criterion_id"], ["criterion.id"], name=op.f("fk_check_result_criterion_id_criterion")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_check_result")),
    )
    op.create_index(
        op.f("ix_check_result_check_run_id"), "check_result", ["check_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_check_result_criterion_id"), "check_result", ["criterion_id"], unique=False
    )
    op.create_table(
        "readiness_report",
        sa.Column("check_run_id", sa.BigInteger(), nullable=False),
        sa.Column("composite_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ready",
                "conditionally_ready",
                "not_ready",
                name="readinessstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "decision",
            sa.Enum("approved", "returned", "rejected", name="reportdecision", native_enum=False),
            nullable=True,
        ),
        sa.Column("share_token", sa.Uuid(), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["check_run_id"],
            ["check_run.id"],
            name=op.f("fk_readiness_report_check_run_id_check_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_readiness_report")),
        sa.UniqueConstraint("check_run_id", name=op.f("uq_readiness_report_check_run_id")),
        sa.UniqueConstraint("share_token", name=op.f("uq_readiness_report_share_token")),
    )
    op.create_table(
        "flag",
        sa.Column("check_result_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("high", "med", "low", name="flagseverity", native_enum=False),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("evidence_excerpt", sa.Text(), nullable=False),
        sa.Column("page_anchor", sa.Text(), nullable=False),
        sa.Column("annotation", sa.Text(), nullable=True),
        sa.Column("overridden", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("override_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["check_result_id"],
            ["check_result.id"],
            name=op.f("fk_flag_check_result_id_check_result"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flag")),
    )
    op.create_index(op.f("ix_flag_check_result_id"), "flag", ["check_result_id"], unique=False)


def downgrade() -> None:
    op.drop_index(op.f("ix_flag_check_result_id"), table_name="flag")
    op.drop_table("flag")
    op.drop_table("readiness_report")
    op.drop_index(op.f("ix_check_result_criterion_id"), table_name="check_result")
    op.drop_index(op.f("ix_check_result_check_run_id"), table_name="check_result")
    op.drop_table("check_result")
    op.drop_index(
        "ix_manuscript_archive_embedding",
        table_name="manuscript_archive",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("manuscript_archive")
    op.drop_index(op.f("ix_criterion_rubric_id"), table_name="criterion")
    op.drop_table("criterion")
    op.drop_index(op.f("ix_check_run_rubric_id"), table_name="check_run")
    op.drop_index(op.f("ix_check_run_manuscript_id"), table_name="check_run")
    op.drop_table("check_run")
    op.drop_index(op.f("ix_rubric_instructor_id"), table_name="rubric")
    op.drop_table("rubric")
    op.drop_index(op.f("ix_manuscript_instructor_id"), table_name="manuscript")
    op.drop_table("manuscript")
    op.drop_table("instructor")
    op.drop_index(op.f("ix_audit_log_check_run_id"), table_name="audit_log")
    op.drop_table("audit_log")  # the trigger drops with its table
    op.execute("DROP FUNCTION audit_log_block_mutation()")
    op.execute("DROP EXTENSION IF EXISTS vector")
